version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  # different jobs are calles later in the workflows sections# different jobs are calles later in the workflows sections
jobs:
  build-and-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      # install node and checkout code
      - node/install:
          node-version: "14.15"
      - aws-cli/setup
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      # - run:
      #     name: Front-End Install Karma Cli
      #     command: |
      #       npm run frontend:karmaCli
      # - run:
      #     name: Front-End Tests
      #     command: |
      #       npm run frontend:test
      # - run:
      #     name: Front-End End-to-end Testing
      #     command: |
      #       npm run frontend:e2e

      # Building the frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # Deploying the frontend to AWS S3
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      # Installing the Backend dependencies
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      # Building the backend
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      # Installing AWS Elastic Beanstalk CLI
      - run:
          name: Installing AWS Elastic Beanstalk CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      # Deploying the backend to AWS Elastic Beanstalk
      - run:
          name: Setting EB environment variables
          command: |
            npm run api:env
      - run:
          name: Back-End Deploy
          command: |
            npm run api:deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: aws
          filters:
            branches:
              only:
                - main
 